### ISSUE TITLE
where to get the train/test file?

### ISSUE THREAD

**Issue by SeekPoint** [Songweiping/GRU4Rec_TensorFlow#1]
PATH_TO_TRAIN = '/PATH/TO/rsc15_train_full.txt'
PATH_TO_TEST = '/PATH/TO/rsc15_test.txt'

**Comment by Songweiping** [comment]
Original files are here: http://2015.recsyschallenge.com/challenge.html
You should process the data with script provided in [hidasib's implementation](https://github.com/hidasib/GRU4Rec/blob/master/examples/rsc15/preprocess.py).
