### ISSUE TITLE
A question about evaluation during training step

### ISSUE THREAD

**Issue by ChenBoSyun** [Songweiping/GRU4Rec_TensorFlow#10]
@Songweiping  您好
很感谢您特地写了一个tensorflow版本的GRU4Rec，真的很浅显易懂
我在每次training step时，用本篇evaluation的方法查看traing时的recall变化
![image](https://user-images.githubusercontent.com/20232369/46338362-91cc9a80-c662-11e8-9cca-f5cb0deab00d.png)
我发现每次recall都接近1
![image](https://user-images.githubusercontent.com/20232369/46338456-ce989180-c662-11e8-8689-cbd2d7504856.png)

请问这样是正常的现象吗

**Comment by Songweiping** [comment]
请问你用的数据集是？这种结果一般而言是不正常的，应该检查一下数据情况。

**Comment by ChenBoSyun** [comment]
@Songweiping 
谢谢您的建议 ，我后来直接用您的程式码跑我的资料集，结果看起来正常很多，看来是我程式码有写错了
![image](https://user-images.githubusercontent.com/20232369/46449904-074e7d00-c7c1-11e8-9dae-36d64c4bbf2f.png)

我用的资料集是kaggle上的电影资料集https://www.kaggle.com/rounakbanik/the-movies-dataset
