### ISSUE TITLE
A question about the column:Session_ID

### ISSUE THREAD

**Issue by chandlervan** [Songweiping/GRU4Rec_TensorFlow#11]
hello Dr.Song,my question is about the session_id.
Should different user share the same session_id? 
let's say if user_a have 5 sessions which has session_id in 0-4,and user_b also have 5 sessions, the session_id of user_b should also be 0-4 or should them be 5-9?
thx
looking forward to your reply

**Comment by Songweiping** [comment]
Each session should have a unique id.

A few more words, users are usually anonymous in session-based recommendation, so we don't know the connection between users and sessions. In this context, session-based recommendation aims to predicting the next item based on previous items in current session, which is independent from a specific user.
