### ISSUE TITLE
关于训练中的loss问题

### ISSUE THREAD

**Issue by DebonairLi** [Songweiping/GRU4Rec_TensorFlow#12]
您好，我在运行这篇文章的代码时，训练的结果是这样的：当lr=0.000017 loss=1.4135（最小），随后当lr=0.000010（之后一直不变），随着step增大，loss也在逐渐增大。这种现象正常吗？或者怎么解释呢？我是这方面的小白，望多包涵。谢谢！

**Comment by Songweiping** [comment]
loss如果先降后升，可能是出现了过拟合(overfitting)。

这个问题似乎与本项目无关，建议移步stackoverflow提问。
