### ISSUE TITLE
MultiRNNCell build

### ISSUE THREAD

**Issue by yhshu** [Songweiping/GRU4Rec_TensorFlow#14]
https://github.com/Songweiping/GRU4Rec_TensorFlow/blob/dd04a89afd26f7ec2a176ae2c519cc6499cd26cc/model.py#L128

When constructing a MultiRNNCell with this statement, tensorflow will prompt that multiple cells are actually sharing weights. 
So I think the correct build method should look like this:

```python
            cells = []
            for i in range(self.layers):
                cell = rnn_cell.GRUCell(num_units=self.rnn_size, activation=self.hidden_act)
                cell = rnn_cell.DropoutWrapper(cell, output_keep_prob=self.dropout_p_hidden)
                cells.append(cell)
            multi_cell = rnn_cell.MultiRNNCell(cells)
```

**Comment by Songweiping** [comment]
It depends. 
Weight sharing is also common to reduce the amount of parameters and to get better generalization. You can use distinct RNNs for multiple layers if it performs better.

**Comment by yhshu** [comment]
Thanks for your explanation.
