### ISSUE TITLE
关于验证集的使用

### ISSUE THREAD

**Issue by Nullees** [Songweiping/GRU4Rec_TensorFlow#16]
请问，代码中为什么没有使用验证集（从训练集中划分出来的验证集）来设置模型训练过程的early stop？貌似代码中的验证过程用的是test数据集 。 @Songweiping

**Comment by Songweiping** [comment]
你好，

1. 这个代码不是为了复现某篇论文的结果，只是提供GRU4Rec这个模型的实现，所以训练和测试数据是服务于模型测试的。如果是想做严谨的实验，请自行修改部分代码。
2. 原作者公布的是Theano代码，我这里只是为了增加相对应的TensorFlow版本，所以基本是按照原项目来写的，原项目中没有使用验证集。
