### ISSUE TITLE
负采样的操作

### ISSUE THREAD

**Issue by Nullees** [Songweiping/GRU4Rec_TensorFlow#17]
在model.py#L136中，注释写道：Use other examples of the minibatch as negative samples.
请问如何通过softmax和sampled_W，sampled_b进行负采样的呢？
水平有限，希望大佬不吝赐教~

**Comment by Songweiping** [comment]
你好，

负采样操作可以这样理解：
假如batch的大小为3，每个样本的下一个item分别为1，2，3，那么输入的self.Y = [1,2,3]。对于第一个样本来说，它的真实label是1，同一个batch中的其他items就作为负样本，即[2,3]为负样本。同理，对于第二个样本，2是它的真实label，[1,3]是它的负样本。以此类推。
