### ISSUE TITLE
Requirements is incomplete

### ISSUE THREAD

**Issue by GnoDGnaF** [Songweiping/GRU4Rec_TensorFlow#2]
Could you explain used python libraries in detail in the Requirements or release a requirements.txt file ?

**Comment by Songweiping** [comment]
The code is written under Python 2.7. Three major libraries are required, e.g. Pandas, Numpy and TensorFlow.

**Comment by GnoDGnaF** [comment]
@Songweiping yeah. 
And the version of pandas must < 0.17.0, because **Dataframe.sort()** is used in your code, which is removed >= 0.17.0(I use 0.16.2 and it get work).

**Comment by Songweiping** [comment]
Thanks for pointing out! Dataframe.sort() is replaced by Dataframe.sort_values() in later versions.
