### ISSUE TITLE
666，Thank you, Dr. Song

### ISSUE THREAD

**Issue by qiufengyu** [Songweiping/GRU4Rec_TensorFlow#5]
特地开 issue 感谢宋博士！
原本还想着自己写个 TF 版本的，巧了！

**Comment by gds123** [comment]
我基于宋博的版本改成dynamic rnn的。
但是recall只有0.43
这是为啥。

**Comment by Songweiping** [comment]
@gds123 
原论文中section3.1.1和figure2已经展示了该模型的训练策略，它不是标准的RNN，没有使用BPTT。根据我之前的经验，使用标准的rnn会使结果更好，如果我没记错的话，recall在0.67左右。你的结果只有0.43应该不是dynamic rnn的问题。

**Comment by gds123** [comment]
@Songweiping 
谢谢回复
dinhthangbkhn/GRU4RecTensorflow  这个仓库也实现了一个dynamic rnn版本得
结果只有0.33.很奇怪

**Comment by ChenBoSyun** [comment]
@Songweiping 

> @gds123
> 原论文中section3.1.1和figure2已经展示了该模型的训练策略，它不是标准的RNN，没有使用BPTT。根据我之前的经验，使用标准的rnn会使结果更好，如果我没记错的话，recall在0.67左右。你的结果只有0.43应该不是dynamic rnn的问题。

你好，請問一下如果您用标准的rnn是指一個session當作一筆training data嗎?

**Comment by Songweiping** [comment]
如果对训练过程有疑问，建议新开issue讨论。
