### ISSUE TITLE
cross_entropy只计算了正例？

### ISSUE THREAD

**Issue by lllmmmyyy** [Songweiping/GRU4Rec_TensorFlow#7]
hi,
请问，在 GRU4Rec.cross_entrop 函数（line 98）中，tf.diag_part 只提取了对角线上的元素，这样是否会导致loss function只计算了正例的loss, 而没有计算负例的loss？

**Comment by Songweiping** [comment]
你好，
在使用cross entropy loss时，实际上是把该问题看作一个多分类（multi-class classification）问题，每个样本的label是在一个batch内同位置所有items上的概率分布，即[0,0,....0,1,0,0,...,0]，因为只有对角线上的概率值对应非0的label，所以只提取对角线上的值即可。这里其它item并不是像bpr loss中“负例”的概念。

**Comment by lllmmmyyy** [comment]
明白了，谢谢！

**Comment by lllmmmyyy** [comment]
还有一个问题，GRU4Rec.fit()函数在训练时，每一个iteration里只对1个time-step的RNN进行了计算，这种迭代方式，导致RNN梯度回传的时候，不会计算前1个time-step以外的参数的梯度，这种训练方式，相较于一个iteration里同时计算多个time-step的结果并且进行训练的方式，哪种会更好一些？

**Comment by Songweiping** [comment]
我个人认为使用标准的BPTT比较好。
可以参考我和原作者的讨论 https://github.com/hidasib/GRU4Rec/issues/8

**Comment by lllmmmyyy** [comment]
了解了，thanks
