### ISSUE TITLE
是否有在实际场景中应用？

### ISSUE THREAD

**Issue by StephenLee2016** [Songweiping/GRU4Rec_TensorFlow#8]
你好，请问这个方法有在真实的推荐场景中使用吗？还有考虑过加入用户维度的信息吗？谢谢

**Comment by StephenLee2016** [comment]
还有考虑过这个模型如何能够支持分布式的tensorflow呢？

**Comment by Songweiping** [comment]
你好，
1. “这个方法有在真实的推荐场景中使用吗？”，我不清楚工业界是否在使用。
2. “考虑过加入用户维度的信息吗？”，个人认为可以。
3. “考虑过这个模型如何能够支持分布式的tensorflow呢？“，我个人还没有考虑这个问题。在真实的推荐场景下，item数量会远远超过论文中10^4这个量级，数据规模也会超过10^7量级，确实可以考虑分布式训练，欢迎讨论或PR。

**Comment by StephenLee2016** [comment]
可以加你微信吗？想和你交流一下

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
