### ISSUE TITLE
data issue

### ISSUE THREAD

**Issue by dinhthangbkhn** [Songweiping/GRU4Rec_TensorFlow#9]
data = pd.merge(data, pd.DataFrame({self.item_key:itemids, 'ItemIdx':self.itemidmap[itemids].values}), on=self.item_key, how='inner')
 After merged with  pd.DataFrame({self.item_key:itemids, 'ItemIdx':self.itemidmap[itemids].values}), the data 's order is based on itemidx order. So I think the code for processing data after is not true.

**Comment by Songweiping** [comment]
Data is sorted by session key and time key (in **_init_** function) again just below the line you mentioned.
